# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u540d\u5b57')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='galley', verbose_name='\u56fe\u7247')),
            ],
        ),
    ]
