# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('wechat_no', models.CharField(max_length=255, verbose_name='\u5fae\u4fe1\u53f7')),
                ('mobile_phone', models.CharField(max_length=255, verbose_name='\u624b\u673a\u53f7')),
                ('supervisor', models.CharField(max_length=255, verbose_name='\u4e0a\u7ea7\u540d\u79f0')),
                ('date', models.DateField(null=True, verbose_name='\u6388\u6743\u65e5\u671f')),
                ('auth_no', models.CharField(max_length=255, verbose_name='\u6388\u6743\u53f7\u7801')),
            ],
        ),
    ]
