# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentauth', '0003_auto_20160915_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='auth_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6388\u6743\u53f7\u7801'),
        ),
    ]
