# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentauth', '0004_auto_20160916_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='agent',
            name='end_date',
            field=models.DateField(null=True, verbose_name='\u7ed3\u675f\u5982\u65e5\u671f'),
        ),
    ]
