# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentauth', '0005_auto_20160921_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='end_date',
            field=models.DateField(null=True, verbose_name='\u7ed3\u675f\u65e5\u671f'),
        ),
    ]
