# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentauth', '0006_auto_20160921_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f'),
        ),
    ]
