# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentauth', '0006_auto_20160921_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u6388\u6743\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e0a\u7ea7\u540d\u79f0'),
        ),
    ]
